In [23]:
import pandas as pd;
import numpy as np;

In [2]:
df = pd.read_csv("patient_data.csv")
df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [8]:
df.columns

Index(['PatientID', 'Name', 'Department', 'Doctor', 'BillAmount',
       'ReceptionistID', 'CheckInTime'],
      dtype='object')

In [14]:
df[["PatientID", "Department", "Doctor", "BillAmount"]]

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [15]:
df2 = df.copy()
df2.drop(columns=["ReceptionistID", "CheckInTime"], inplace=True)
df2

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [17]:
df.isnull().sum()

PatientID         0
Name              0
Department        0
Doctor            0
BillAmount        2
ReceptionistID    0
CheckInTime       0
dtype: int64

In [3]:
df.fillna({"BillAmount":df.BillAmount.mean()}, inplace=True)
df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,5925.0,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,5925.0,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [4]:
df.groupby("Department")["BillAmount"].sum()

Department
Cardiology     16200.0
Dermatology     5925.0
Neurology       5925.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [5]:
df.drop_duplicates(inplace = True)

In [6]:
billing_df = pd.read_csv("billing_data.csv")
billing_df

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [20]:
merged_df = pd.merge(df, billing_df,on="PatientID",how="inner")
merged_df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,5925.0,2,2023-01-11 10:30,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00,3000,3200
4,105,Eva,Dermatology,Dr. Rose,5925.0,2,2023-01-14 08:45,1000,4000

In [21]:
additional_rows = [
    [107, "Kevin", "Cardiology", "Dr. Moses", 12000.0, 1, "2024-02-06 10:00", 7000, 5000],
    [108, "Sophia", "Neurology", "Dr. Ramesh", 18500.0, 3, "2024-02-07 15:45", 12000, 6500],
    [109, "Arjun", "Orthopedics", "Dr. Mehta", 7600.0, 2, "2024-02-08 09:20", 4000, 3600],
    [110, "Mia", "Dermatology", "Dr. Kavitha", 5400.0, 1, "2024-02-08 13:10", 5400, 0],
    [111, "Noah", "ENT", "Dr. Prakash", 6800.0, 2, "2024-02-09 11:05", 3000, 3800],
    [112, "Aarav", "Gastroenterology", "Dr. Iyer", 15400.0, 1, "2024-02-10 16:25", 8000, 7400],
    [113, "Emma", "Pediatrics", "Dr. Ambrose", 9200.0, 3, "2024-02-11 10:50", 5000, 4200],
    [114, "Liam", "General Medicine", "Dr. Shah", 4500.0, 1, "2024-02-11 14:00", 4500, 0],
    [115, "Ananya", "Gynecology", "Dr. Priya", 13200.0, 2, "2024-02-12 09:40", 6000, 6200],
    [116, "Ethan", "Psychiatry", "Dr. Rao", 8900.0, 1, "2024-02-12 12:30", 3000, 5900]
]


new_df = pd.DataFrame(additional_rows, columns=merged_df.columns)
merged_df = pd.concat([merged_df, new_df], ignore_index=True)

In [22]:
merged_df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,5925.0,2,2023-01-11 10:30,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00,3000,3200
4,105,Eva,Dermatology,Dr. Rose,5925.0,2,2023-01-14 08:45,1000,4000
5,107,Kevin,Cardiology,Dr. Moses,12000.0,1,2024-02-06 10:00,7000,5000
6,108,Sophia,Neurology,Dr. Ramesh,18500.0,3,2024-02-07 15:45,12000,6500
7,109,Arjun,Orthopedics,Dr. Mehta,7600.0,2,2024-02-08 09:20,4000,3600
8,110,Mia,Dermatology,Dr. Kavitha,5400.0,1,2024-02-08 13:10,5400,0
9,111,Noah,ENT,Dr. Prakash,6800.0,2,2024-02-09 11:05,3000,3800
10,112,Aarav,Gastroenterology,Dr. Iyer,15400.0,1,2024-02-10 16:25,8000,7400
11,113,Emma,Pediatrics,Dr. Ambrose,9200.0,3,2024-02-11 10:50,5000,4200
12,114,Liam,General Medicine,Dr. Shah,4500.0,1,2024-02-11 14:00,4500,0
13,115,Ananya,Gynecology,Dr. Priya,13200.0,2,2024-02-12 09:40,6000,6200
14,116,Ethan,Psychiatry,Dr. Rao,8900.0,1,2024-02-12 12:30,3000,5900

In [27]:
pd.concat([df, billing_df.loc[:,"InsuranceCovereed":"FinalAmount"]], axis=1)

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101.0,Alice,Cardiology,Dr. Smith,5000.0,1.0,2023-01-10 09:00,NaN,NaN
1,102.0,Bob,Neurology,Dr. John,5925.0,2.0,2023-01-11 10:30,NaN,NaN
2,103.0,Charlie,Orthopedics,Dr. Lee,7500.0,1.0,2023-01-12 11:00,NaN,NaN
3,104.0,David,Cardiology,Dr. Smith,6200.0,3.0,2023-01-13 12:00,NaN,NaN
4,105.0,Eva,Dermatology,Dr. Rose,5925.0,2.0,2023-01-14 08:45,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0,3000.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500.0,3500.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2500.0,5000.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,3200.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,4000.0